In [ ]:
#NUMPY


In [ ]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))

b= np.array([3,4,5])
print(b)

[1 2 3]
<class 'numpy.ndarray'>
[3 4 5]


In [ ]:
x= np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
u=np.ones((4,3))
print(u)
#filling the whole array with 1

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
y= np.full((7,7), 7)
#fills the whole array with given value
print(y)

[[7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]]


In [ ]:
p=np.arange(10,30,5)
print(p)

# np.arange(start value , end value , difference)

#or


print(np.linspace(0,2,4))
#generates the evenly distributed array from(0,2, 4 ters)


[10 15 20 25]
[0.         0.66666667 1.33333333 2.        ]


In [ ]:
print(np.arange(0,2,0.3))



[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [ ]:
print(np.random.rand(4,3))
#creates an array with random shape

[[0.61383217 0.82355951 0.26393486]
 [0.93764986 0.97599455 0.94478713]
 [0.69626584 0.78102275 0.35712684]
 [0.34928085 0.77180428 0.53977253]]


In [ ]:
a = np.array([[1., 0., 0.], [0., 1., 2.]])
print(a.ndim)# returns dimension of array
print(a.shape)# return the shape(rows ,col)
print(a.size)# returns number of elements
print(a.dtype)#return the type of array

2
(2, 3)
6
float64


In [ ]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

print(b.resize(2,3))

[[1 2 3]
 [4 5 6]]
None


In [ ]:
a=np.array([1,2,4,6,7,8,])
print(a[1:3])
#print(arrayname[starting index : ending index +1])
a[1:5]=-1#can assign value to an slice in numpy
print(a)

[2 4]
[ 1 -1 -1 -1 -1  8]


In [ ]:
a = np.array([1, 2, 5, 7, 8])

a_slice = a[1:5]

a_slice[1] = 1000

print(a)
#modifiying the slice of an array also
#modifies the original array
# To prevent this we must copy array first


another_slice=a[2:6].copy()
print(another_slice)

[   1    2 1000    7    8]
[1000    7    8]


In [ ]:
# Accesing An array
# Accessing specific elements
b=np.array([[1,2,3],[4,5,6]])

print(b[1, 2])
# row 1, col 2

# Accessing whole rows

print(b[1, :])
# row 1, all columns

# Accessing whole columns
print(b[:, 1])
# all rows, column 1


6
[4 5 6]
[2 5]


In [ ]:
a = np.arange(12).reshape(3, 4)

rows_on = np.array([True, False, True])
a[rows_on ,:]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [44]:
import numpy as np
A=np.array([1,2,3])
B=np.array([[1,2,3],[4,5,6]])
def multiply_loops(A, B):

  C = np.zeros((A.shape[0], B.shape[1]))
  for i in range(A.shape[1]):

      for j in range(B.shape[0]):

        C[i, j] = A[i, j] * B[j, i]
  return C



#OR

def multiply_vector(A, B):

  return A @ B

print(multiply_loops(A,B))


IndexError: tuple index out of range

In [49]:
#Addition of arrays in Numpy
a=np.array([12,3,4,5])
b=np.array([7,3,4,5])
#b=np.array([7]) # adds 7 in all the elements
c=a+b
print(c)


[19  6  8 10]


In [51]:
a=np.array([20,30,40,50])
b=np.arange(1,5,1)#start , end , diff
print(b)
c=a//b
print(c)

[1 2 3 4]
[20 15 13 12]


In [53]:
a=np.array([20,30,40,50])
b=np.arange(1,5,1)#start , end , dif
print(b)
c=a**b
print(c)


[1 2 3 4]
[     20     900   64000 6250000]


In [ ]:
m = np.array([20, -5, 30, 40])

# Element-wise comparison
m < [15, 16, 35, 36]

# Scalar comparison

m < 25



# Filtering: Get elements below 25

m[m < 25]


In [58]:
#broadCasting
#The size od array must much if it does not then broadcasting
#streaches the array to match the size of another array to perform given array

a=np.array([[0,1,2],[3,4,5]])
a + [100,200,300]
b=([[10],[20]])
print(a)
print()
print(a+b)


[[0 1 2]
 [3 4 5]]

[[10 11 12]
 [23 24 25]]


In [62]:
m1 = np.arange(6).reshape(2,3)#method to define an array with 2 rows and 3 columns from 1 to 5
#total 6 elements
print(m1)
print()

m1.T#Transposing matrix


[[0 1 2]
 [3 4 5]]



array([[0, 3],
       [1, 4],
       [2, 5]])

In [66]:
a = np.arange(6).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


<function ndarray.max>

In [74]:
marks = np.array([45, 78, 62, 90, 55])
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
result =marks>66
print(result)



66.0
90
45
[False  True False  True False]


In [81]:
temp = np.array([30, 32, 35, 38, 33])

print(np.max(temp))
print((temp*1.8)+32)
result= temp > 34
print(np.sum(temp>34))

38
[ 86.   89.6  95.  100.4  91.4]
2


In [97]:
# Convert the list to a NumPy array
sales = np.array([
    [200, 250, 300, 280, 260], # Shop 1
    [180, 220, 270, 260, 240], # Shop 2
    [210, 260, 310, 290, 270]  # Shop 3
])

# Task 1: Find total sales of each shop (sum across each row)
total_sales_per_shop = np.sum(sales, axis=1)
print(f"Total sales per shop: {total_sales_per_shop}")
# Output: [1290 1170 1340]

# Task 2: Find the shop with highest total sales
# np.argmax returns the index of the highest value (0, 1, or 2)
# We add 1 to make it human-readable (Shop 1, 2, or 3)
best_shop_index = np.argmax(total_sales_per_shop)
print(f"Shop with highest sales: Shop {best_shop_index + 1} (Total: {total_sales_per_shop[best_shop_index]})")
# Output: Shop 3 (Total: 1340)

# Task 3: Find the average sales per day (mean down each column)
avg_sales_per_day = np.mean(sales, axis=0)
print(f"Average sales per day: {avg_sales_per_day}")
# Output: [196.66666667 243.33333333 293.33333333 276.66666667 256.66666667]


Total sales per shop: [1290 1170 1340]
Shop with highest sales: Shop 3 (Total: 1340)
Average sales per day: [196.66666667 243.33333333 293.33333333 276.66666667 256.66666667]


In [90]:
prices = np.array([150, 450, 600, 800, 300])
prices=prices+prices*0.1
print(prices)
result=prices>500
print(result)
discounted_prices = np.where(prices > 500, prices * 0.8, prices)
print(discounted_prices)


[165. 495. 660. 880. 330.]
[False False  True  True False]
[165. 495. 528. 704. 330.]


In [106]:
attendance = np.array([
[1, 1, 1, 0, 1],
[1, 0, 1, 1, 1],
[0, 1, 1, 0, 1],
[1, 1, 1, 1, 1],
[1, 0, 0, 1, 1]
])
total = np.sum(attendance, axis=1)
print(total)
below = np.where(total < 4)[0]
print(f"Indices of students below 4: {below}")
max_index = np.argmax(total)
print(f"Index of max attendance: {max_index}")


[4 4 3 5 3]
Indices of students below 4: [2 4]
Index of max attendance: 3
